package com.soaproject.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.destination
     *
     * @mbggenerated
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.delivery_info
     *
     * @mbggenerated
     */
    private String deliveryInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_description
     *
     * @mbggenerated
     */
    private String orderDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.weight
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_score
     *
     * @mbggenerated
     */
    private Integer orderScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.destination
     *
     * @return the value of order.destination
     *
     * @mbggenerated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.destination
     *
     * @param destination the value for order.destination
     *
     * @mbggenerated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.delivery_info
     *
     * @return the value of order.delivery_info
     *
     * @mbggenerated
     */
    public String getDeliveryInfo() {
        return deliveryInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.delivery_info
     *
     * @param deliveryInfo the value for order.delivery_info
     *
     * @mbggenerated
     */
    public void setDeliveryInfo(String deliveryInfo) {
        this.deliveryInfo = deliveryInfo == null ? null : deliveryInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_description
     *
     * @return the value of order.order_description
     *
     * @mbggenerated
     */
    public String getOrderDescription() {
        return orderDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_description
     *
     * @param orderDescription the value for order.order_description
     *
     * @mbggenerated
     */
    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription == null ? null : orderDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.weight
     *
     * @return the value of order.weight
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.weight
     *
     * @param weight the value for order.weight
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.start_date
     *
     * @return the value of order.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.start_date
     *
     * @param startDate the value for order.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_score
     *
     * @return the value of order.order_score
     *
     * @mbggenerated
     */
    public Integer getOrderScore() {
        return orderScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_score
     *
     * @param orderScore the value for order.order_score
     *
     * @mbggenerated
     */
    public void setOrderScore(Integer orderScore) {
        this.orderScore = orderScore;
    }
}